# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 506bc91284f5b37d9980f147a5f7bec3fd5879ca72f078b961218df4cbaafba870708fe2765e36d68b831d2a1ae2c1a1bbcdfe7f8871f72605277789d1a500ef

test:
  secret_key_base: d9435277c166a71b4e52037f65c2bc6d61cbfa8823c743a6d4074d010fbc4a1c62d41104d480424f3e26cc4bb8dc535ad4ce2b98460a5d45743f5df7ef033d5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
